import NavBar from '@/components/NavBar'
import './globals.css'

import { Russo_One as Russo } from 'next/font/google'
import { Quicksand } from 'next/font/google'

const russo = Russo({ subsets: ['latin'], weight: ['400'], variable: '--font-russo' })
const quicksand = Quicksand({ subsets: ['latin'], weight: ['400'], variable: '--font-quicksand'})

export const metadata = {
  title: 'Tryme',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${russo.variable} ${quicksand.variable} font-russo overflow-x-hidden bg-base`}>
        <NavBar />

        <main className='w-screen flex flex-col justify-center items-center'>
          {children}
        </main>
      </body>
    </html>
  )
}
