import './globals.css'
import { Russo_One as Russo } from 'next/font/google'

const russo = Russo({ subsets: ['latin'], weight: ['400'], variable: '--font-russo' })

export const metadata = {
  title: 'Tryme',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${russo.variable} font-russo`}>
        {children}
      </body>
    </html>
  )
}
